name: google_map_submodule
description: "Shared Google Maps logic for multiple Flutter projects."
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.3.0
  cloud_functions: ^5.1.0
  firebase_auth: ^5.7.0
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2   
  geocoding: ^3.0.0
  http: ^1.0.0
  protobuf: ^3.1.0
